const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Behaviors.Platform,
		C3.Behaviors.bound,
		C3.Behaviors.scrollto,
		C3.Plugins.Keyboard,
		C3.Behaviors.Sin,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Mouse,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Behaviors.Platform.Cnds.OnJump,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Behaviors.Platform.Cnds.IsFalling,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Platform.Acts.SetVectorY,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Acts.GoToLayoutByName
	];
};
self.C3_JsPropNameTable = [
	{Background: 0},
	{Sólido: 0},
	{Plataforma: 0},
	{Fixar: 0},
	{Animação: 0},
	{RestritoAoLayout: 0},
	{CentrarEm: 0},
	{Jogador: 0},
	{Teclado: 0},
	{Senóide: 0},
	{Premio: 0},
	{Âncora: 0},
	{Pontuação: 0},
	{Ação: 0},
	{Inimigo1: 0},
	{Marcador: 0},
	{Cactus: 0},
	{FimFase1: 0},
	{AperteEpacoProximaFase: 0},
	{Áudio: 0},
	{TelaInicial: 0},
	{Mouse: 0},
	{TelaGameOver: 0},
	{AperteEspaco: 0},
	{GameOver: 0},
	{BackgroundFase2: 0},
	{PlataformaFase2: 0},
	{AguaFase2: 0},
	{CaixaFase2: 0},
	{Inimigo2: 0},
	{Arvore: 0},
	{CogumeloVenenoso: 0},
	{PlanoDeFundoEmBlocos: 0},
	{ImagemNinjaVitoria: 0},
	{FundoPreto: 0},
	{NinjaFimDeJogo: 0},
	{TrofeuVitoria: 0},
	{TextoVitoriaNinja: 0},
	{TextoNinjaCampeao: 0},
	{ReiniciarJogo: 0},
	{BonusPrimeiraFase: 0},
	{AperteEspacoParaFase2: 0},
	{Botao: 0},
	{FaseAtual: 0},
	{PontuacaoInicialFase: 0}
];

self.InstanceType = {
	Background: class extends self.ITiledBackgroundInstance {},
	Plataforma: class extends self.ITiledBackgroundInstance {},
	Animação: class extends self.ISpriteInstance {},
	Jogador: class extends self.ISpriteInstance {},
	Teclado: class extends self.IInstance {},
	Premio: class extends self.ISpriteInstance {},
	Pontuação: class extends self.ITextInstance {},
	Inimigo1: class extends self.ISpriteInstance {},
	Marcador: class extends self.ISpriteInstance {},
	Cactus: class extends self.ISpriteInstance {},
	FimFase1: class extends self.ISpriteInstance {},
	AperteEpacoProximaFase: class extends self.ITextInstance {},
	Áudio: class extends self.IInstance {},
	TelaInicial: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	TelaGameOver: class extends self.ISpriteInstance {},
	AperteEspaco: class extends self.ITextInstance {},
	GameOver: class extends self.ITextInstance {},
	BackgroundFase2: class extends self.ITiledBackgroundInstance {},
	PlataformaFase2: class extends self.ISpriteInstance {},
	AguaFase2: class extends self.ISpriteInstance {},
	CaixaFase2: class extends self.ISpriteInstance {},
	Inimigo2: class extends self.ISpriteInstance {},
	Arvore: class extends self.ISpriteInstance {},
	CogumeloVenenoso: class extends self.ISpriteInstance {},
	PlanoDeFundoEmBlocos: class extends self.ITiledBackgroundInstance {},
	ImagemNinjaVitoria: class extends self.ISpriteInstance {},
	FundoPreto: class extends self.ITiledBackgroundInstance {},
	NinjaFimDeJogo: class extends self.ISpriteInstance {},
	TrofeuVitoria: class extends self.ISpriteInstance {},
	TextoVitoriaNinja: class extends self.ITextInstance {},
	TextoNinjaCampeao: class extends self.ITextInstance {},
	ReiniciarJogo: class extends self.ITextInstance {},
	BonusPrimeiraFase: class extends self.ITextInstance {},
	AperteEspacoParaFase2: class extends self.ITextInstance {},
	Botao: class extends self.ISpriteInstance {}
}